MG\Domain\Model\Ad\Ad:
  type: entity
  table: mg_ad
  repositoryClass: MG\Infrastructure\Domain\Model\Ad\DoctrineAdRepository
  id:
    adId:
      column: id
      type: AdId
  fields:
    telephone:
      type: string
    content:
      type: text
    userId:
      type: UserId
      column: user_id
    createdOn:
      column: created_on
      type: datetime
    updatedOn:
      column: updated_on
      type: datetime
